Native terminal support
codingteam/euclid pull request #9
Opened 2018-11-18 02:03 UTC by hagane

Well this escalated fast. As per discussion in #6 Euclid now can happily live in all kinds of weird native terminals. Please note that native console rendering will not work properly when launched with SBT (probably because app's IO is wrapped by SBT or something) and will crash if started in an IDE (no actual console window). I'm still a fan of AWT terminal emulation. Yet it does resolve #5 in letter and in spirit, so there's that.

2018-11-18 05:15 UTC, ForNeVeR commented on jvm/src/main/scala/com/googlecode/lanterna/terminal/WindowsTerminal.scala
> +  setTerminalMode(Wincon.STD_INPUT_HANDLE, 0x0200) //ENABLE_VIRTUAL_TERMINAL_INPUT
I suggest to extract that constant into a named variable.

2018-11-18 05:26 UTC, ForNeVeR commented on jvm/src/main/scala/com/googlecode/lanterna/terminal/WindowsTerminal.scala
> +      throw new RuntimeException(s"WinAPI call error: 0x$errCode")
It would be a good idea to call `FormatMessage` here, but we can do that later (in case it really becomes a problem).

2018-11-18 05:31 UTC, ForNeVeR commented on shared/src/main/scala/ru/org/codingteam/euclid/io/Display.scala
> +  def draw(x: Int, y: Int, ch: String, fg: Color[ColorImpl] = null, bg: Color[ColorImpl] = null): Unit
Why not make these arguments `Option`s? You're wrapping them into `Option` every time you use them anyway.

2018-11-18 05:36 UTC, ForNeVeR commented
> native console rendering will not work properly when launched with SBT (probably because app's IO is wrapped by SBT or something) and will crash if started in an IDE (no actual console window)

We can deal with that later (detect that there're some exceptional circumstances and select a fallback terminal based on that). For now that'll be okay, I guess.

2018-11-18 05:40 UTC, ForNeVeR requested changes
There're minor issues. Let's resolve them and merge.

2018-11-18 17:49 UTC, hagane commented
>detect that there're some exceptional circumstances and select a fallback terminal based on that.
Lanterna already does that for the most part, if nobody forces it to create a particular type of terminal.

2018-11-19 17:02 UTC, merged

2018-11-19 17:03 UTC, ForNeVeR commented
Thanks for the contribution!